version: "3.2"
services:
  postgres:
    networks:
      - mynetwork
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  myappcontainer:
    networks:
      - mynetwork
    image: myapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgres:5432/test
networks:
  mynetwork: